import type { Metadata } from 'next'
import './globals.css'
import { CssBaseline, ThemeProvider } from '@mui/material'
import theme from '@/theme/theme'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <CssBaseline />
        <ThemeProvider theme={theme}>{children}</ThemeProvider>
      </body>
    </html>
  )
}
