import type { Metadata } from 'next'
import './globals.css'
import { CssBaseline } from '@mui/material'
import ThemeProviderWrapper from '@/components/ThemeProvider/ThemeProviderWrapper'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <CssBaseline />
        <ThemeProviderWrapper>{children}</ThemeProviderWrapper>
      </body>
    </html>
  )
}
